import type { BusinessConfig } from '#/types'

export const businessListData: BusinessConfig[] = [
  {
    id: 'penguin_saldejums_uzvaras',
    baseCost: 750,
    baseIncome: 5,
    name: 'Penguin Saldējums',
    description: 'A colorful ice cream truck strategically parked in Uzvaras Parks. Perfect for refreshing families and kids after a skateboarding session.',
    location: 'Uzvaras Parks',
  },
  {
    id: 'arancino_riga_agenskalns',
    baseCost: 2500,
    baseIncome: 15,
    name: 'Arančino Rīga',
    description: 'Artisan arancini shop located inside the beautiful, renovated Āgenskalns indoor market (Āgenskalna tirgus). Blends Sicilian street food with the Latvian spirit.',
    location: 'Āgenskalns',
  },
  {
    id: 'kiosk_vermanes_darzs',
    baseCost: 6000,
    baseIncome: 32,
    name: 'Vērmanes Kafija Kiosk',
    description: 'A small but bustling coffee and cereal bar kiosk in the historic Vērmanes dārzs park. The favorite pit stop for downtown commuters.',
    location: 'Vērmanes dārzs',
  },
  {
    id: 'pizza_tallinas_kvartals',
    baseCost: 14000,
    baseIncome: 70,
    name: 'Tallinas Kvartāls Maiznīca',
    description: 'Artisan pizza shop in the heart of the Tallinas creative district. Attracts hipsters, artists, and lovers of organic baked goods.',
    location: 'Tallinas Kvartāls',
  },
  {
    id: 'pancake_kalnciema',
    baseCost: 28000,
    baseIncome: 125,
    name: 'Kalnciema Pankūkas',
    description: 'A cozy spot specializing in sweet and savory pancakes, nestled among the characteristic wooden houses of the Kalnciema kvartāls Saturday market.',
    location: 'Kalnciema',
  },
  {
    id: 'cafe_miera_iela',
    baseCost: 55000,
    baseIncome: 220,
    name: 'Miera Iela Hipster Cafē',
    description: 'Literary cafe and independent roastery on Riga\'s most alternative street. Great atmosphere for students and matcha tea lovers.',
    location: 'Brasa (Miera iela)',
  },
  {
    id: 'tech_bistro_teika',
    baseCost: 120000,
    baseIncome: 450,
    name: 'Teika Tech Bistro',
    description: 'A modern fast-casual bistro located in the Jaunā Teika technology hub. Feeds hundreds of hungry programmers and startup founders every lunch break.',
    location: 'Jaunā Teika',
  },
  {
    id: 'sunset_grill_andrejosta',
    baseCost: 260000,
    baseIncome: 900,
    name: 'Andrejosta Sunset Grill',
    description: 'Elegant restaurant with a terrace overlooking the Daugava river in the marina area. Generates massive profits during summer evenings thanks to the sunset view.',
    location: 'Andrejosta',
  },
  {
    id: 'fine_dining_vecriga',
    baseCost: 580000,
    baseIncome: 1800,
    name: 'Vecrīga Luxury Dining',
    description: 'Haute cuisine restaurant located in a historic building in the Old Town. An exclusive destination for wealthy tourists, gala dinners, and diplomatic delegations.',
    location: 'Vecrīga',
  },
  {
    id: 'airport_food_court',
    baseCost: 1350000,
    baseIncome: 3800,
    name: 'Lidosta Rīga Food Empire',
    description: 'The pinnacle of your commercial empire: an entire block in the food court of Riga International Airport. Guaranteed customer traffic 24/7.',
    location: 'Mārupe (Lidosta Rīga)',
  }
];